### PR TITLE
feat: make ClearButton build again, unblock CCX

### PR DESCRIPTION
**Pull request by lazd**
## How and where has this been tested?
 - **How this was tested:** 
 - **Browser(s) and OS(s) this was tested with:** 

## To-do list

- [x] Make ClearButton build
- [x] Make Tag use ClearButton
- [x] Make Search/SearchWithin use ClearButton
- [x] Update to spectrum-tokens@8.0.0
- [x] Fix tag
- [x] Make an `overBackground` or `staticColor` ClearButton for Toast and Tag - used only in Toast
- [x] Decide whether we manually set the color of the ClearButton icon in Tag, or we tell people to add the `overBackground` class - Manually setting
- [x] Merge and release DSS PR https://git.corp.adobe.com/Spectrum/dss/pull/362
- [ ] Validate everything @GarthDB @pfulton

### CODE REVIEW

**Comment by lazd** [comment]
@GarthDB Did you happen to run the VRT? Let's get this one in ASAP.

**Comment by pfulton** [comment]
I ran VRT locally, and got 25 failures. For several of them, it looks like it failed because the clear button was added in places where it previously didn't exist.

However, the positioning in the Toast component looks off:

Screen Shot 2021-11-03 at 3 14 35 PM

**Comment by lazd** [comment]
Ok @pfulton we need to merge and release https://git.corp.adobe.com/Spectrum/dss/pull/362, then this PR should be ready.

**Comment by GarthDB** [comment]
Tooltip has changed:
Reference:
image

Test:
image

**Comment by lazd** [comment]
@pfulton fixed that last issue, once [VRT completes here](https://spectrum-visual-regression.ci.corp.adobe.com/view/Spectrum%20CSS/job/spectrum-css-vr-essential-test/35/) I think we can merge this and be off to the races with CCX!

**Comment by lazd** [comment]
@GarthDB, yup Tooltip changed. During workshop, @badimon told us that "Tooltip has the same shape as ActionButton and no longer has a custom icon size or padding," so we made it inherit and it changed accordingly. Looks much nicer now!

**Comment by GarthDB** [comment]
Same with Toast with clear button:
Reference:
image

Test:
image

**Comment by lazd** [comment]
@GarthDB yup that's actually Toast in the wrapping example page, https://github.com/adobe/spectrum-css/pull/1304/commits/bb014ca9bad2b187e0409d0d3339688bf528d293 fixes it.

**Comment by lazd** [comment]
The docs site has been deployed to https://git.corp.adobe.com/pages/lawdavis/spectrum-css-ccx-verify/docs/clearbutton.html for verification. Thanks @badimon!

**Review by badimon — APPROVED** [review]

**Pull request merged**
