### PR TITLE
fix: slider thumb inner background issue, fixes #1133

### LINKED ISSUE #1133: Slider thumb inner background should not be transparent
## Description

For sliders with a ramp or tick, the circle thumb shows the ramp or tick behind it.

## Steps to reproduce

spectrum-css:

Screen Shot 2021-02-10 at 2 40 31 PM

## Expected behavior

Design spec:

Screen Shot 2021-02-10 at 2 39 11 PM

## Screenshots

See above.

## Environment
 - **Spectrum CSS version:** @spectrum-css/slider@3.0.0
 - **Browser(s) and OS(s):** Chrome 88

## Additional context
n/a

### PR DESCRIPTION
**Pull request by BaileyMcKelway**
This fixes any issue where the thumb of a slider is transparent when it should be opaque.
## Description

Fixes #1133 

Changed background for spectrum-Slider-handle class.

## How and where has this been tested?
 - **How this was tested:** 
  Tested by building locally and navigating to http://localhost:3000/docs/slider.html#slider and viewing behavior of thumb.
 - **Browser(s) and OS(s) this was tested with:** 
Chrome 89 - Mac 10.15
## Screenshots

Ramp
Ticks
Range
Ticks+Label

https://user-images.githubusercontent.com/25776618/111511276-f4c42600-8724-11eb-9385-f1f942ffed53.mov
https://user-images.githubusercontent.com/25776618/111511290-f857ad00-8724-11eb-8b39-4013bfa0cc78.mov

## To-do list

- [X] If my change impacts other components, I have tested to make sure they don't break.
- [X] If my change impacts documentation, I have updated the documentation accordingly.
- [X] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [X] This pull request is ready to merge.

### CODE REVIEW

**Comment by BaileyMcKelway** [comment]
I'm getting this error from Travis that I can't find a solution for.

Screen Shot 2021-03-19 at 3 50 27 PM

**Comment by jianliao** [comment]
I restarted the job.

**Comment by castastrophe** [comment]
I suspect PR #1547 will end up superseding this so I've highlighted this PR there to ensure changes address this concern.

**Comment by castastrophe** [comment]
I suspect PR #1547 will end up superseding this so I've highlighted this PR there to ensure changes address this concern.

**Comment by bernhard-adobe** [comment]
> I suspect PR #1547 will end up superseding this so I've highlighted this PR there to ensure changes address this concern.

@castastrophe I pinged PJ to weight in as we currently don't have this documented in the Tokens package nor the Tokens Design Documentation. (Ramp and Ticks is not in there yet).
Screen Shot 2023-01-11 at 20 52 43
@BaileyMcKelway is correct here, we should ensure in these 2 cases for Ramp and Tick that the Ticks and Slider Ramp is not visible. 

I will make the updates to #1547

**Comment by bernhard-adobe** [comment]
For Range, I already took care of this in PR #1547 
Screen Shot 2023-01-11 at 21 05 09

**Comment by bernhard-adobe** [comment]
I added this to PR #1547

**Comment by castastrophe** [comment]
Closing this PR out so we can address it in our tokens migration work but super appreciate the work done here to help us find a solution.

**Pull request closed without merging**
