### PR TITLE
Tabs Overflow Example

### PR DESCRIPTION
**Pull request by NateBaldwinDesign**
## Description

Updated the example of how to handle overflowing tabs based on the updated guidelines. "When there are too many tabs to fit horizontally across the viewport, the tabs component can be displayed as a quiet dropdown."

## Related Issue

https://github.com/adobe/spectrum-css/issues/58

## Motivation and Context

This example is necessary to aid in proper implementations across component libraries

## Screenshots (if appropriate):
image

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by lazd** [comment]
Well that's a whole heck of a lot simpler. Thanks @NateBaldwinDesign!

**Comment by Harbs** [comment]
The doc was confusing to me.

The screenshot of the spec had no extra space for more tabs, but the doc does.

I'm assuming the tabs are supposed to collapse one by one as there becomes less space for them, so if there's room for three tabs and there's a total of 5, the third tab becomes a dropdown for 3, 4 and 5) as shown, while tabs 1 and 2 are normal tabs. Is this correct?

If yes, the generated docs could be clearer. (If no, they could be clearer too...) ;)

**Comment by NateBaldwinDesign** [comment]
As soon as there is no room to display any single tab item, all tab items are placed within the dropdown displayed in the screenshot above. The single "tab" that is visible changes it's label depending on the selected tab item. For example, looking at the screenshot above, if the user selects "Tab 3" that respective tab content will be displayed and the Tabs component will have the label "Tab 3". This interaction is consistent with our dropdown.

**Comment by Harbs** [comment]
Thanks. I'd suggest making the docs a bit clearer.

**Pull request merged**
