### PR TITLE
chore: build tool tweaking

### PR DESCRIPTION
**Pull request by misterbrownlee**
## How and where has this been tested?
 - **How this was tested:** 
 - **Browser(s) and OS(s) this was tested with:** 

## To-do list

- [x] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [ ] I have tested these changes in Windows High Contrast mode.

- [x] This pull request is ready to merge.

### CODE REVIEW

**Review by pfulton — APPROVED** [review]

**Comment by bernhard-adobe** [comment]
confirming fix of:

- Multiple instances of browser-sync & dev serve running on same machine for different code bases.  
Screen Shot 2022-08-23 at 16 54 02
- Recover after YAML syntax error 
Screen Shot 2022-08-23 at 17 04 57


confirming nice to have fixes reported in CSS-233:
- error log for tokens that are not in use like creating  
```CSS
.spectrum-ActionButton {
  --spectrum-actionbutton-dev-tools-test: var(--spectrum-border-width-100); 
}
  ```
  creates this log which can be confusing when working on multiple tokens at the same time:
```
[17:13:47] 'checkSourceCSS' errored after 75 ms
[17:13:47] Error: @spectrum-css/actionbutton defines --spectrum-actionbutton-dev-tools-test, but never uses it
    at DestroyableTransform.doBake [as _transform] (/Users/bschmidt/work/spectrum-css/tools/component-builder-simple/css/index.js:185:19)
[17:13:47] Error running 'actionbutton:buildMedium': Error: @spectrum-css/actionbutton defines --spectrum-actionbutton-dev-tools-test, but never uses it
``` 

There are still hard-errors that stop the dev server and require a restart if forgetting braces like:
```CSS
.spectrum-ActionButton {
  background-color: red

.spectrum-Test {
 ...

}
```
Screen Shot 2022-08-25 at 14 47 36

**Comment by misterbrownlee** [comment]
@bernhard-adobe and @pfulton I'm going to try and take on the error around matching braces. I couldn't get it to hang up when leaving out braces on my build, but I'll try that exact snippet. Seeing it's `checkSourceCSS` is helpful, as is knowing it's an unhanded promise rejection.

For the listing out unused vars, I don't know how to make it less confusing, because I'm not confused... but if you could suggest a better way to call those out we can try to change how it displays those messages.

**Comment by bernhard-adobe** [comment]
> @bernhard-adobe and @pfulton I'm going to try and take on the error around matching braces. I couldn't get it to hang up when leaving out braces on my build, but I'll try that exact snippet. Seeing it's `checkSourceCSS` is helpful, as is knowing it's an unhanded promise rejection.
> 
> For the listing out unused vars, I don't know how to make it less confusing, because I'm not confused... but if you could suggest a better way to call those out we can try to change how it displays those messages.

Awesome, thank you Aaron.
Yeah I think the logging of un-used vars is a preferences. It's ok for now.

**Review by bernhard-adobe — APPROVED** [review]
I am approving this to get some of those fixes already in the codebase. the rest can come when it is ready or addressed . @misterbrownlee feel free to merge!
Thank you for your contribution!

**Pull request merged**
