### PR TITLE
Added CEP7 gulp task so Autoprefixer works with older Chromium

### PR DESCRIPTION
**Pull request by Harbs**
Added cep7 gulp task

## Description
Added a gulp task to support Chromium 41.x used in CEP7 and earlier

## Related Issue
#88 

## Motivation and Context
Many -webkit- prefixes are needed for CEP7 that are not generally needed for modern browsers. The additional gulp task allows a special build to be run for CEP panel developers.

## How Has This Been Tested?
The cep7 target was run locally and tested on Chromiuim 41.0.2272.118

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Harbs** [comment]
There might be a simpler way to create the gulp task than what I did. I'm not exactly a gulp expert...

It also might make sense adding to the readme that CEP panel developers should run `gulp cep7` if they are developing panels for CC 2017 and earlier.

**Comment by lazd** [comment]
This is very duplicative and will be hard to maintain if we ever make changes to the build script. Gulp is just JavaScript, so you can export functions, share them between tasks, etc to avoid duplication. 

That said, I would much rather see a way to pass a custom autoprefixer configuration like @GarthDB suggested than another task specific to CEP.

**Comment by Harbs** [comment]
What do you think of my latest commit? Building for cep7 can be done by `gulp --cep7`

**Comment by lazd** [comment]
@Harbs much better! But I think we can do even more... Maybe we can pass an arg to define the location of a package.json that contains [`browserslists`](https://github.com/browserslist/browserslist#queries)... I'm not sure what the right way to do this is... Let's explore it...

**Comment by lazd** [comment]
Hey @harbs, is this something you still need? If so, let's look into the `.browserslistrc` option mentioned above. Thanks!

**Comment by lazd** [comment]
Let's go ahead and close this for now, we can rebase and re-open if this is still an issue.

**Pull request closed without merging**
