### PR TITLE
feat: RTL Support

### LINKED ISSUE #390: Handle Logical Directions
## Description
CSS has a feature in the works for logical directions, instead of left or right, you can use start or end.
These are the changes that we'll need https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties/Basic_concepts

width -> inline-size
height -> block-size
padding-left -> padding-inline-start
padding-right -> padding-inline-end
padding-top -> padding-block-start
padding-bottom -> padding-block-end
left -> inset-inline-start
right -> inset-inline-end
top -> inset-block-start
bottom -> inset-block-end
border-left -> border-inline-start
border-left-color -> border-inline-start-color
... etc
text-align :left -> text-align: start;
text-align :right -> text-align: end;
resize: horizontal -> resize: inline;
resize: vertical -> resize: block;

## Why do you need this feature or component?
We must support both LTR and RTL

### PR DESCRIPTION
**Pull request by lazd**
## Description

This pull request implements RTL support and closes #390 

### Complete

* [x] Accordion
* [x] Alert
* [x] Asset
* [x] Asset List
* [x] Avatar
* [x] Banner
* [x] Bar Loader
* [x] Breadcrumbs
* [x] Button
* [x] ButtonGroup
* [x] Calendar
* [x] Card
* [x] Checkbox
* [x] Circle Loader
* [x] Coach Mark
* [x] Cycle Button
* [x] Dialog
* [x] Drop Indicator
* [x] Dropdown
* [x] FieldLabel
* [x] Icon
* [x] IllustratedMessage
* [x] InputGroup
* [x] Menu
* [x] Miller Columns
* [x] Popover
* [x] Quick Actions
* [x] Radio
* [x] Rating
* [x] Rule
* [x] Search
* [x] Sidenav
* [x] Site
* [x] SplitButton
* [x] SplitView
* [x] StatusLight
* [x] Stepper
* [x] Switch
* [x] Table
* [x] Tabs
* [x] Textfield
* [x] Toast
* [x] Treeview
* [x] Typography
* [x] Well
* [x] StepList
* [x] Pagination - Added `spectrum-Pagination-nextButton` and `spectrum-Pagination-prevButton` for button style examples
* [x] Slider - supports switch from LTR to RTL, but not the other way around

### Discussion required

* [x] Tooltip - labels and icons render nicely, but `left`/`right`/`bottom`/`top` variants are physical, not logical. More discussion required with the React team to see if we want to replace this.

### Support not required

* [x] Dropzone
* [x] FieldGroup
* [x] Label
* [x] Link
* [x] Underlay

## How and where has this been tested?
 - **How this was tested:** Lots of scrolly scroll. Pro tip: Hit `Control + R` to go to RTL, `Control + N` to go back to LTR 😎 
 - **Browser(s) and OS(s) this was tested with:** Chrome on macOS

See the docs site here: https://git.corp.adobe.com/pages/lawdavis/spectrum-css-rtl/docs/

<a name="designreview"></a>
### Design Review

Every component was checked against the Spectrum documentation to ensure it conforms to Internationalization Guidelines, if present.

#### Key:
✅- Conforms
✴️- Not a stable component, no guidelines
⚠️- Stable component, no guidelines

#### Components

* ⚠️ Accordion - no guidelines, conforms to result of [conversation on slack](https://adobedesign.slack.com/archives/GEN034MAS/p1581612832022000)
* ✴️ Alert - no guidelines (contribution)
* ✴️ Asset - no guidelines (contribution)
* ✴️ Asset List - no guidelines (contribution)
* ✅ Avatar - n/a (contribution)
* ✴️ Banner - no guidelines (Badge contribution)
* ✅ Bar Loader - conforms to guidelines. Note: Percent sign must be moved manually
* ✴️ Breadcrumbs - no guidelines (contribution)
* ⚠️ Button - no guidelines, [pinged on slack](https://adobedesign.slack.com/archives/GEN034MAS/p1583341517076400)
* ✅ ButtonGroup - n/a
* ✴️ Calendar - no guidelines (contribution)
* ⚠️ Card - no guidelines
* ✅ Checkbox - conforms to guidelines.
* ✅ Circle Loader - conforms to guidelines.
* ✅ Coach Mark - conforms to guidelines. Note: `x of y` text must be manually mirrored (default directionality will make it `of y x`, examples include `<bdo dir="ltr">2 of 8</bdo>` to override this)
* ✅ Combobox - conforms to guidelines.
* ✅ Cycle Button - n/a (contribution)
* ⚠️ Datepicker - conforms to Combobox, no guidelines (contribution)
* ✅ Dialog - conforms to guidelines.
* ✅ Drop Indicator - n/a (Drag and Drop contribution)
* ✅ Dropdown - conforms to guidelines.
* ✅ FieldLabel - conforms to Textfield guidelines.
* ⚠️ Form - no guidelines, may need insight on label position in the future
* ⚠️ Icon - no guidelines, but probably n/a
* ✴️ IllustratedMessage - no guidelines, but probably n/a (contribution)
* ✴️ Label - no guidelines (Badge contribution)
* ✅ Menu - conforms to Dropdown guidelines.
* ✅ Meter - conforms to Bar Loader guidelines.
* ✴️ Miller Columns - no guidelines (contribution)
* ✴️ Pagination Button - no guidelines (contribution)
* ✴️ Pagination Explicit - no guidelines (contribution)
* ✴️ Pagination Page - no guidelines (contribution)
* ⚠️ Popover - no guidelines
* ⚠️ Quick Actions - no guidelines
* ✅ Radio - conforms to guidelines.
* ⚠️ Rating - no guidelines
* ✅ Rule - n/a
* ✅ Search - no guidelines
* ✅ Sidenav - conforms to guidelines.
* ✴️ Site - no guidelines (K9 Panels contribution)
* ✴️ SplitButton - no guidelines (contribution)
* ✴️ SplitView - no guidelines (not even a contribution, no idea why this exists)
* ✅ StatusLight - conforms to guidelines.
* ✴️ Stepper - no guidelines (Numeric Stepper Field contribution)
* ✅ Switch - conforms to guidelines.
* ✅ Table - conforms to guidelines.
* ✅ Tabs - conforms to guidelines.
* ✅ Textfield - conforms to guidelines.
* ✅ Toast - conforms to guidelines.
* ✴️ Treeview - no guidelines (contribution)
* ✅ Typography - n/a
* ✅ Tooltip - conforms to guidelines, [discussed on slack](https://adobedesign.slack.com/archives/GELPLC8NR/p1583286438080900)
* ✴️ Well - no guidelines (Wells contribution)
* ✴️ StepList - no guidelines (contribution)
* ✅ Slider - conforms to guidelines. Note: Percent sign must be moved manually

## Screenshots

image

## To-do list

- [x] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x] Check for Spectrum RTL guidelines for each component, ensure we're following them
- [x] File issues against Design on JIRA for anything we need their help or insight from
- [x] Fix DecoratedTextfield icon issue
- [x] Fix Checkbox position in Card
- [x] Merge and release halo focus #603 
- [ ] Fix documentation Dialog button position issues https://opensource.adobe.com/spectrum-css-vr-results/5a85e25-result-2020-03-06_17-57-42/dist/docs/dialog.html
- [ ] This pull request is ready to merge.

### CODE REVIEW

**Comment by bernhard-adobe** [comment]
I added a VR test for this to inspect the default view. https://spectrum-visual-regression.ci.corp.adobe.com/job/spectrum-css-vr-test-asset/230/artifact/spectrum-css/backstop_data/html_report/index.html

There are a couple of default visual issues before RTL:

- did you intentionally increase the viewbox of the component previews?
Screen Shot 2020-02-24 at 15 25 32

- first chevron of the calendar is flipped
Screen Shot 2020-02-24 at 15 25 13

- Miller columns are now cutting of the left-sided icons
Screen Shot 2020-02-24 at 15 24 32

- toggles have increase in width
Screen Shot 2020-02-24 at 15 40 47


Could you please maybe not set the entire documentation to RTL?
I remember @NateBaldwinDesign  asked to only have the component preview switched to RTL.
I see this screenshot 
https://user-images.githubusercontent.com/201344/74490054-30365600-4e7c-11ea-9ca9-2266ee757014.png

This PR will also have a **significant impact** how we write our CSS. Instead of using left, right top and widths we now have to use inset etc. 
I am wondering why we have to progress with our own custom implementation where we are breaking-change every component and not use a more commonly used extension like RTLCSS
https://rtlcss.com/learn/usage-guide/options/

**Comment by lazd** [comment]
Good catches, @bernhard-adobe!

## Viewbox of component previews

That looks wrong. It should not have that fixed height. Will fix.

## Calendar icons

I saw that one myself and noted to fix it already. Thanks!

## Miller columns

Good catch!

## Toggles

I had to refactor some of the stuff RSP V3 had added for RTL support on the animations, looks like I messed something up. Good catch!

## Entire documentation to RTL

I will try to address that. Note that, if we do this, we need to be CERTAIN that any `:dir(rtl)` specific hacks come after the `:dir(ltr)`, otherwise this will break.

It is much more reliable to set the entire document to RTL, as that is closer to how things will happen in the wild.

## RTL affecting how we write CSS

We're not writing a custom implementation for this at at all. In fact, we're not using the [W3 specification for Logical Properties](https://drafts.csswg.org/css-logical/). See the [MDN article on Logical Directions](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Handling_different_text_directions) for an introduction to the new properties.

We did not write our own plugin for this, we're using the [`postcss-logical` plugin](https://www.npmjs.com/package/postcss-logical) to implement this specification, which is over 3 years old and has 2.2 million weekly downloads.

The RTLCSS approach is backwards to how we do things; it takes the old way of writing CSS and makes it work with RTL by generating a separate stylesheet. We want to do the opposite; we want to write CSS the way we'll be writing CSS in the future (with logical properties), and use PostCSS plugins to transform that code to work in the old way (like we do with Babel in the JS world).

I agree that it's a big change, but this prepares us for the future by letting us write future-CSS today. This is the PostCSS way, and exactly what we do/did with Custom Properties, Nesting, Focus Ring, etc. It's going to be hard for our brains, but it's better in the long run! In the mean time, I wrote a Sublime Text plugin that helps me transform the old style `left`/`border-left`/`width` etc into the new style to assist my learning, it's really helpful.

**Comment by lazd** [comment]
New visual regression test: https://spectrum-visual-regression.ci.corp.adobe.com/job/spectrum-css-vr-test-asset/231/artifact/spectrum-css/backstop_data/html_report/index.html

**Comment by jianliao** [comment]
Decorated TextField Multiline example, the alert icon is shift out of the textarea.
image

**Comment by jianliao** [comment]
Card component, the checkbox is not center.
image

**Comment by jianliao** [comment]
@lazd Calendar
image

**Pull request merged**
