### PR TITLE
High contrast links

### LINKED ISSUE #1125: secondary links appearing as text color not link color in WHCM
## Description
Secondary links are appearing as text color not link color in WHCM

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/link.html
2. Use Edge , Win 10 , Windows High Contrast Mode on
3. Observe secondary link (both quiet and non) are text color not link color

## Expected behavior
Should be link color as shown in https://spectrum.adobe.com/static/Windows-High-Contrast-Kits/Link-WindowsHighContrast.xd

## Environment
 - **Spectrum CSS version:**  2.13.0
 - **Browser(s) and OS(s):** Edge 88.0 on Win 10

### PR DESCRIPTION
**Pull request by jnurthen**
Forced secondary colors to linkText color
## Description
Resolves #1125 

## How and where has this been tested?
 - **How this was tested:**  Using steps in issue #1125
 - **Browser(s) and OS(s) this was tested with:** Edge 88.0 on Windows 10 in WHCM

## Screenshots
Link - Spectrum CSS and 2 more pages - Work - Microsoft​ Edge Beta 2_1_2021 3_31_46 PM

## To-do list

- [ ] If my change impacts other components, I have tested to make sure they don't break.
- [ ] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x] This pull request is ready to merge.

### CODE REVIEW

**Comment by dgodon** [comment]
@jnurthen Are you expecting to complete this soon?

**Comment by jnurthen** [comment]
@GarthDB @lazd any chance this can get merged?

**Comment by GarthDB** [comment]
@jnurthen I'll dig into it in the coming sprint. I'll need to update it with the DNA-7.0 work and make sure it all works there too.

**Comment by GarthDB** [comment]
@jnurthen I moved these changes to a new pr to fix the rebasing conflicts. https://github.com/adobe/spectrum-css/pull/1168

**Pull request closed without merging**
