### PR TITLE
WIP Update index.css removing remaining !important(s)

### PR DESCRIPTION
**Pull request by tacoelho**
!important removal.

## Description

!important removal as requested on issue #238 

## To-do list

- [x ] If my change impacts other components, I have tested to make sure they don't break.
- [x ] If my change impacts documentation, I have updated the documentation accordingly.
- [ x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x ] This pull request is ready to merge.

### CODE REVIEW

**Comment by GarthDB** [comment]
@tacoelho thanks for starting this work. If you want to, you can add WIP to your pr title and we will wait until you're done to review it. If it's ready for review now, let us know.

**Comment by lazd** [comment]
@GarthDB can you take a look at this one? IIRC you did some work on the Checkbox focus styles and were able to refactor it to not use `!important`.

**Comment by tacoelho** [comment]
> @tacoelho thanks for starting this work. If you want to, you can add WIP to your pr title and we will wait until you're done to review it. If it's ready for review now, let us know.

Hi there, ready for review :)

**Comment by GarthDB** [comment]
@tacoelho I'm sorry, I should have made the issue clearer. The `!importants` are doing something right now. Just taking them out actually breaks the component in some way. The example of the calendar. Just taking out the `border-bottom: none !important;` makes it look like a dotted underline shows up.

Here's a screenshot of the current Calendar component on https://opensource.adobe.com/spectrum-css/2.13.0/docs/#calendar :
image

Here's a screenshot of the Calendar from this pull request:
image

So moving forward, if you're still comfortable working on it, I would recommend comparing the component between your fork and the current release to make sure that removing the `!important` doesn't break something visually.

To make things easier, I would also recommend making a pr for each component you work on. It would be easier to review and they aren't really impacting eachother.

**Comment by tacoelho** [comment]
> @tacoelho I'm sorry, I should have made the issue clearer. The `!importants` are doing something right now. Just taking them out actually breaks the component in some way. The example of the calendar. Just taking out the `border-bottom: none !important;` makes it look like a dotted underline shows up.
> 
> Here's a screenshot of the current Calendar component on https://opensource.adobe.com/spectrum-css/2.13.0/docs/#calendar :
> image
> 
> Here's a screenshot of the Calendar from this pull request:
> image
> 
> So moving forward, if you're still comfortable working on it, I would recommend comparing the component between your fork and the current release to make sure that removing the `!important` doesn't break something visually.
> 
> To make things easier, I would also recommend making a pr for each component you work on. It would be easier to review and they aren't really impacting each other.

Hi @GarthDB 
That would require more time and more attention. The best approach would be refactoring all the css files to get rid of these !importants and finding where some rules are overriding others. That would make the code more easier to maintain and compliable with modern css standards.

**Comment by lazd** [comment]
I'm going to go ahead and close this PR as each of these cases will require individual attention. Thanks @tacoelho!

**Pull request closed without merging**
