### PR TITLE
[IE11] fix dropdown and menu width

### PR DESCRIPTION
**Pull request by geej**
## Motivation and Context
IE11 compatibility for dropdowns.

## Issue
#74 

## How Has This Been Tested?
In VM (Windows 10 IE11), OS X (Chrome latest)

## Screenshots (if appropriate):
screen shot 2019-01-16 at 10 58 13 am

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by geej** [comment]
@adobe/open-source-office

**Comment by stevengill** [comment]
@geej I sent you an invitation to join this org (github.com/adobe). Accept the invitation and close and re-open this PR. The CLA check will re-run and should pass

**Comment by geej** [comment]
@adobe/open-source-office

**Comment by geej** [comment]
@stevengill thanks!

**Comment by lazd** [comment]
@geej excellent. This is [a classic Flexbug](https://github.com/philipwalton/flexbugs#flexbug-4) -- IE 11 ignores the entire `flex` property if you use the shorthand.

**Comment by lazd** [comment]
@geej excellent. This is [a classic Flexbug](https://github.com/philipwalton/flexbugs#flexbug-4) -- IE 11 ignores the entire `flex` property if you use the shorthand.

**Pull request merged**
