### PR TITLE
chore(popover): update popover stories

### PR DESCRIPTION
**Pull request by mlogsdon18**
## Description

- This updates the Popover stories to include an Action Button as the trigger source for the Popover to allow for a better visual. 
- Updates the Spectrum Website link for popover on the docs site from `popovers` to `popover`
- Adds an onclick event to activate the popover for the story
- Updates a few other components to pass through functions for content to account for an error that the Interaction add-on was causing (IllustratedMessage, Dialog, Card)

## To test

1. Run Storybook for this PR and navigate to the Popover story
2. Click the button to open the Popover
3. Change the position of the Popover and make sure that it updates accordingly (you will have to close and reopen the popover as the positioning is done with javascript on button click)

## To-do list

- [x] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [x] I have tested these changes in Windows High Contrast mode.
- [x] I have updated any relevant storybook stories and templates.

- [x] This pull request is ready to merge.

### CODE REVIEW

**Comment by mlogsdon18** [comment]
Currently, adding the @storybook/addon-interactions causes an error when we are using other storybook templates as content for another story. For example, the Popover story has a Menu as the content and this cause an error. I did not have any luck finding a solution so any help would be greatly appreciated!

**Review by pfulton — CHANGES_REQUESTED** [review]
Thanks for taking this on! I know it was a slightly larger chunk of work than we initially thought.

Regarding the position of the Popover after invoking it: I'm wondering if we should set some value other than `0` for `--spectrum-popover-cross-offset` and use that in conjunction with the calculation you use to position the Popover.

Without it, the tip overlaps the button
Screenshot 2023-07-27 at 4 38 09 PM

**Comment by mlogsdon18** [comment]
@pfulton Alright I made some updates here and renamed the variables to [match the spec ](https://spectrum.adobe.com/page/popover/#Offset). The default for the offset is supposed to be 8px so I've updated that as well and the stories look better. Let me know what you think!

**Comment by pfulton** [comment]
Beta release published: `@spectrum-css/popover@7.0.0-beta.0`

**Comment by mlogsdon18** [comment]
@pfulton with the updates I made this had 0 VRT issues in SWC! So I think we should be good to get this merged!

**Pull request merged**
