### PR TITLE
build: add vars as a peerDep, fixes #413

### LINKED ISSUE #413: component builder missing a dependency
## Description
Using the component builder, we ran into an issue where we were missing @spectrum-css/vars
Should probably be a dependency of some sort?

## Steps to reproduce

1. Clone react spectrum
2. remove package.json reference to spectrum-css/vars and maybe from yarnlock as well
3. yarn install
4. build storybook

```
(node:1146) UnhandledPromiseRejectionWarning: Error: Cannot find module '@spectrum-css/vars'
Require stack:
- /home/circleci/react-spectrum-v3/node_modules/@spectrum-css/component-builder/css/lib/varUtils.js
- /home/circleci/react-spectrum-v3/node_modules/@spectrum-css/component-builder/css/plugins/postcss-custom-properties-mapping.js
- /home/circleci/react-spectrum-v3/node_modules/@spectrum-css/component-builder/css/processors.js
- /home/circleci/react-spectrum-v3/postcss.config.js
- /home/circleci/react-spectrum-v3/.storybook-v3/webpack.config.js
- /home/circleci/react-spectrum-v3/node_modules/@storybook/core/dist/server/utils/server-require.js
- /home/circleci/react-spectrum-v3/node_modules/@storybook/core/dist/server/common/custom-presets.js
- /home/circleci/react-spectrum-v3/node_modules/@storybook/core/dist/server/config.js
- /home/circleci/react-spectrum-v3/node_modules/@storybook/core/dist/server/build-static.js
- /home/circleci/react-spectrum-v3/node_modules/@storybook/core/server.js
- /home/circleci/react-spectrum-v3/node_modules/@storybook/react/dist/server/build.js
- /home/circleci/react-spectrum-v3/node_modules/@storybook/react/bin/build.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.resolve (internal/modules/cjs/helpers.js:74:19)
    at Object.<anonymous> (/home/circleci/react-spectrum-v3/node_modules/@spectrum-css/component-builder/css/lib/varUtils.js:110:47)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/circleci/react-spectrum-v3/node_modules/@spectrum-css/component-builder/css/plugins/postcss-custom-properties-mapping.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
(node:1146) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1146) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

### PR DESCRIPTION
**Pull request by lazd**
## Description

This PR declares `@spectrum-css/vars` as a `peerDependency` in `@spectrum-css/component-builder` so uses outside of Spectrum CSS will be aware that it is required.

## How and where has this been tested?
 - **How this was tested:** n/a
 - **Browser(s) and OS(s) this was tested with:** n/a

## To-do list

- [x] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x] This pull request is ready to merge.

### CODE REVIEW

**Comment by lazd** [comment]
@snowystinger This is the best representation of the relationship between `component-builder` and `vars` I could come up with. Please let me know if this addresses #413 for you. Thanks!

**Comment by lazd** [comment]
@snowystinger can you verify this one is good to merge?

**Comment by snowystinger** [comment]
so this is where it's used
https://github.com/adobe/spectrum-css/blob/master/tools/component-builder/css/vars.js#L37

and npm's stance on peer is:
>Peer dependencies are a special type of dependency that would only ever come up if you were publishing your own package.
>Having a peer dependency means that your package needs a dependency that is the same exact dependency as the person installing your package. This is useful for packages like react that need to have a single copy of react-dom that is also used by the person installing it.

We use our own vars, not @spectrum-css/vars. So it should probably be a dependency. That, or our build still needs more work.

**Comment by lazd** [comment]
@snowystinger so the way this package is primarily used is as a dependency of a given component, itself must depend on a specific version of `vars`. The component builder should use the `vars` dependency as installed by the component itself, not its own version. So it's not quite the same as npm's use case here, but I believe it meets the criteria.

In the case of using your own `vars`, we have the same situation. It should *not* install a different copy of vars, it should be using yours. So, if you have a monorepo setup, and `vars` is part of it, and `component-builder` is installed, it should resolve to your version of vars and work as expected. The `peerDependency` will give you warning, and all should be well with the cosmos, yes?

**Comment by lazd** [comment]
I'll go ahead and merge this PR, and we can talk about what we can do in the React Spectrum monorepo to fix the issue you're having with linking. Thanks!

**Pull request merged**
