### PR TITLE
build: support live-reload for token custom value changes (CSS-225)

### PR DESCRIPTION
**Pull request by lazd**
## Description

Make `watch` work with Tokens

### CODE REVIEW

**Review by pfulton — COMMENTED** [review]
✅ the watcher is now picking up changes made to these files. Awesome!

I noticed that if I try to use a newly defined token in the custom dirs, components (I tried with ActionButton) aren't aware of them without stopping & restarting the server. Is there anything we could do to make them aware w/o having to stop and restart?

One more thing: would we be able to add the `<component>/themes/*` files to the watcher as well?

**Comment by bernhard-adobe** [comment]
@lazd yeah, I think we need also the files in the `themes` folder to be watched.
Screen Shot 2022-07-21 at 14 53 34

**Comment by bernhard-adobe** [comment]
Added the watching of the new themes folder for the Core-Tokens migration

**Comment by bernhard-adobe** [comment]
@lazd follow up if you could answer it:
Do you have suggestions how to place the CSS files in the folder `components/commons` under watch as well?

**Pull request merged**
