### PR TITLE
Rating - Adds container around icons for visible keyboard focus

### PR DESCRIPTION
**Pull request by Martskin**
For Issue #249

# Adds container around `spectrum-Rating-icon` icons for visible keyboard focus

## Description
In order to preview the focus state of the Rating component this PR adds a container around `spectrum-Rating-icon` icons for visible keyboard focus using a `.focus-ring + &` sibling selector.

Screen Shot 2019-10-11 at 3 28 24 PM

### CODE REVIEW

**Comment by Martskin** [comment]
Just realized `spectrum-Rating-input` is inside of `spectrum-Rating` and that's not valid. Refactoring....

**Comment by Martskin** [comment]
Refactored and push.

**Comment by lazd** [comment]
Thanks for the contribution, @Martskin! So #249 is more about showing the already implemented behavior in the docs site, with a simple JS enhancement. Your PR makes it possible to show focus purely with CSS, which enables partial interactivity, but I think we can do this real quick in JS. I'll go ahead and close this and push a branch with the enhancement so we show focus.

**Comment by lazd** [comment]
Superseded by https://github.com/adobe/spectrum-css/pull/373

@Martskin, can you please take a look at that?

**Pull request closed without merging**
