### PR TITLE
Add handling for soon to exist logical directions

### PR DESCRIPTION
**Pull request by snowystinger**
and do a small component in example

## Description

This implements Logical Directions with PostCSS
https://github.com/adobe/spectrum-css/issues/390

## How and where has this been tested?
 - **How this was tested:** 
 - **Browser(s) and OS(s) this was tested with:** 

## To-do list

- [ ] If my change impacts other components, I have tested to make sure they don't break.
- [ ] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [ ] This pull request is ready to merge.

### CODE REVIEW

**Comment by lazd** [comment]
This is awesome. So we can merge this, then go through the rest of the components in a subsequent pull request.

If we can do this to each component without making breaking changes, that would be ideal.

Then, for everything that requires a breaking change for RSP V3, we should do that separately, after this is added. That will ensure we can get RTL support out to the maximum number of products.

**Comment by snowystinger** [comment]
Btw, this will likely be a breaking change. It requires applications to have at least a top level element with the `dir` attribute. It generates CSS for [LTR] and [RTL] and because it might be
`border-left` in LTR it'd be `border-right` in RTL

**Comment by lazd** [comment]
Hmm, interesting @snowystinger. Why can't we have it dump out no `dir` for LTR, and `[dir=rtl]` for RTL? If the existing PostCSS plugin can't do that, let's contribute that capability. There is no explicit reason why this _must_ be a breaking change, it just sounds like a limitation of the tooling.

**Comment by snowystinger** [comment]
@devongovett Did you find the place where you found this info?

As for why, my understanding is that if you have

.classname {
  border-left: 3px;
}

[dir=rtl] .classname {
  border-right: 3px;
}

the rtl would actually need to do something to undo border-left, but i think that's a hard problem to solve because you can't just set it to zero or initial or inherit because that might interfere with other selectors styling

**Comment by GarthDB** [comment]
We need to schedule this with other breaking changes.

**Comment by lazd** [comment]
Superseded by #532, which includes the commit from this PR. Thanks for blazing the trail, @snowystinger!

**Pull request closed without merging**
