### PR TITLE
Actionbar popover width fixed

### PR DESCRIPTION
**Pull request by sambhavkaul**
## Description

Added the relative width in actionbar popover as mentioned in #319 

## How and where has this been tested?
 - **How this was tested:** Using steps in issue #319 
 - **Browser(s) and OS(s) this was tested with:** 

## To-do list

- [x] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x] This pull request is ready to merge.

### CODE REVIEW

**Comment by lazd** [comment]
@GarthDB @bernhard-adobe @jianliao how do we feel about introducing a CSS custom property that's not in DNA, as a mechanism for customization? This is effectively API as we're using it here. The other option is to add a variant `.spectrum-ActionBar--flexible`, that sets `width: auto` (as proposed by @Westbrook).

**Comment by lazd** [comment]
@sambhavkaul can you please update your pull request to remove the `--spectrum-actionbar-width` variable, leaving it as `100%` by default, then add the following:

```css
.spectrum-ActionBar--flexible {
  .spectrum-ActionBar-popover {
    width: auto;
  }
}
```

Then, please add a new example to `components/actionbar/metadata/actionbar.yml` showing usage of the `.spectrum-ActionBar--flexible` class.

Once that is done, we can merge this PR. Thanks!

**Comment by lazd** [comment]
@Westbrook updated this PR to use `.spectrum-ActionBar--flexible` for this use case and added an example. I think we're good to go, please let me know if this will work for you and I'll go ahead and merge.

**Comment by Westbrook** [comment]
LGTM. Thanks e'rybody!

**Pull request merged**
