### PR TITLE
fix(link): correct highcontrast custom properties

### PR DESCRIPTION
**Pull request by lunarfusion**
## Description
This corrects link colors in Windows High Contrast mode.

- Jira issue CSS-333 https://jira.corp.adobe.com/browse/CSS-333

## How and where has this been tested?
 - Using Chrome emulation of WHCM + dark mode. You can replicate this test by opening the rendering drawer in Chrome dev tools (Command + P, search "rendering", open the rendering drawer) and activating prefers-color-scheme: dark and forced-colors: active.

 -  Chrome 108 for macOS

## Screenshots

Screen Shot 2022-12-12 at 3 53 41 PM
Screen Shot 2022-12-12 at 3 53 45 PM
Screen Shot 2022-12-12 at 3 53 50 PM
Screen Shot 2022-12-12 at 3 53 59 PM
Screen Shot 2022-12-12 at 3 54 07 PM

**Primary keyboard focus:**
Screen Shot 2022-12-12 at 3 55 18 PM

## To-do list

- [ ] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [x] I have tested these changes in Windows High Contrast mode.

- [ ] This pull request is ready to merge.

### CODE REVIEW

**Review by pfulton — APPROVED** [review]
This looks great. Thanks for taking care of this.

**Comment by pfulton** [comment]
@Westbrook - mind taking a quick look at this to see if we've solved it?

**Review by Westbrook — APPROVED** [review]
This looks much more like what I expect.

Are we sure we don't loose anything with the lack of `CanvasText` and `ButtonText` values on the right?

**Comment by lunarfusion** [comment]
@Westbrook regarding the removal of CanvasText and ButtonText, I made that revision after referring to the XD design specs for Link in WHCM located at https://spectrum.adobe.com/page/link/#Windows-high-contrast-mode. Screenshot here:

Screen Shot 2022-12-13 at 1 48 39 PM

It appears that all links and link decorations are intended to be identical in color. Note that the teal backgrounds are not present in WHCM, and I have pointed this out to design.

**Pull request merged**
