### PR TITLE
Removed extra g tags

### PR DESCRIPTION
**Pull request by Harbs**
Removed extra tags

## Description
Self explanatory

## Related Issue
#69 
## Motivation and Context
Simplifies the svg

## How Has This Been Tested?
Changed it locally, and the output is visually identical.
## Types of changes
-[x] Pedantic change.

## Checklist:
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Harbs** [comment]
I signed the CLA and it's still showing this error...

**Comment by stevengill** [comment]
I'll investigate cla failure

**Comment by stevengill** [comment]
Still failing!

**Comment by stevengill** [comment]
CLA check has been fixed! Thanks for your patience. It is a new system. Found and fixed a bug thanks to this PR!

**Comment by Harbs** [comment]
Great. Glad to be of service. 😄

**Comment by lazd** [comment]
Thanks for this! The `<g>` tags are indeed in error. Note that this asset is just a demonstration asset and is meant to be customized by the user.

**Pull request merged**
