### PR TITLE
✨RSP-629 - Fill Slider - with Offset

### PR DESCRIPTION
**Pull request by sakshigupta**

### CODE REVIEW

**Comment by GarthDB** [comment]
@NateBaldwinDesign do we want to include this? Was there any design review?
image

**Comment by GarthDB** [comment]
@sakshigupta what's the use case for it?

**Comment by NateBaldwinDesign** [comment]
Yes, the offset typically occurs at the 50% mark, where the user can make adjustments to increase/decrease properties (such as in photography editing) starting from an origin point. 

Likewise, there are scenarios where users may apply a preset and then make adjustments to the preset configurations. In that use-case, a product may want to have the fill originate from the position on the slider defined by the preset as a way of showing the user how much they've deviated from the preset they originally selected.

**Comment by GarthDB** [comment]
@devongovett are you ok with the js used here to implement the offset?

**Comment by GarthDB** [comment]
@NateBaldwinDesign thanks!

**Comment by devongovett** [comment]
Doesn't seem to me like we need the JS in spectrum-css for it. Could just hard code the offsets in the doc examples.

**Comment by GarthDB** [comment]
@devongovett do you think this dom setup would work with how you would want to do the js in react?

**Comment by devongovett** [comment]
made a simplified version in https://github.com/adobe/spectrum-css/pull/116

**Comment by sakshigupta** [comment]
Closing it, as its no longer required

**Pull request closed without merging**
