### PR TITLE
docs(accordion): addresses issue with disabled state in storybook

### PR DESCRIPTION
**Pull request by jenndiaz**
## Description
Currently in [Storybook for Accordion](https://opensource.adobe.com/spectrum-css/preview/?path=/story/components-accordion--default&args=disableAll:!true), when you toggle "disabled" to true in the control panel, accordion items still open and close. They should not be toggle-able when disabled. 

Changes: 
- Update name for the `disableAll` control to be more clear 
- Remove ability to click accordion items when `disableAll === true` 
- Expand chromatic coverage to include a `disableAll` example 

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

Open [accordion in storybook ](https://pr-2458--spectrum-css.netlify.app/preview/?path=/story/components-accordion--default)
- [x] When disable all items is true all accordion items are disabled @mdt2 
- [x] When disable all items is true no accordion items are toggle-able @mdt2 

- [x] Chromatic includes a disable all example

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [x] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [x] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## To-do list

- [ ] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

### CODE REVIEW

**Review by jawinn — APPROVED** [review]
Looks good to me as well.

I'm wondering why the VRT results are not showing a change, despite the new version of accordion being totally different than the snapshot with the addition of the all disabled variation (looks that way in Chromatic between canvas and snapshot). I'd expect one change that needs to be accepted?

**Comment by jenndiaz** [comment]
> Looks good to me as well.
> 
> I'm wondering why the VRT results are not showing a change, despite the new version of accordion being totally different than the snapshot with the addition of the all disabled variation (looks that way in Chromatic between canvas and snapshot). I'd expect one change that needs to be accepted?

I noticed this too, I tried rerunning them and again they are passing without needing to be accepted.

**Comment by pfulton** [comment]
Let's see if rebasing your branch against the most recent stuff in `main` helps fix the Chromatic issue. I think we merged in a config change after you created this branch, so updating things might just work!

**Comment by pfulton** [comment]
@jenndiaz looks like it caught it now!

**Pull request merged**
