### PR TITLE
fix(tooltip): rtl places tip in correct position

### PR DESCRIPTION
**Pull request by mdt2**
## Description

This PR aims to address issue #2707 by adjusting the left and right positions of the Tooltip for RTL. Also included is an updated Chromatic kitchen sink story to increase VRT coverage.

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps
- [x] Head over to Storybook and turn on the [testing preview for Tooltip](https://64762974a45b8bc5ca1705a2-qgypyyjwyz.chromatic.com/?path=/story/components-tooltip--default&globals=testingPreview:!true). You should see all the options for tooltip placement there
- [x] When you switch to RTL, all the tip placements should be touching the body of the tooltip
- [x] When you switch to RTL, the left and right tooltips are facing the correct way (which I believe should be opposite in RTL, so if the heading says "left" the tooltip should be to the right of the imaginary source when RTL is on)
- [x] Check [the docs site](https://pr-2736--spectrum-css.netlify.app/tooltip) in LTR and RTL. Confirm no regressions, specifically for "show on hover" section

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## To-do list

- [ ] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [ ] I have updated relevant storybook stories and templates.
- [ ] I have tested these changes in Windows High Contrast mode.
- [ ] If my change impacts **other components**, I have tested to make sure they don't break.
- [ ] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

### CODE REVIEW

**Review by rise-erpelding — APPROVED** [review]
This looks great! I'm approving because this fixes the bug and the Chromatic coverage is a big improvement! 🎉 

I have a question about something that existed before and may not necessarily need to be fixed:
I find these Bottom Left/Bottom Right/Top Left/Top Right tooltips very confusing when they're presented in rtl (see screenshots below). It does make sense if they're supposed to flip directions in rtl so that they're not actually left or right, but thought it would be good to confirm that's how we want them while we're here.
image
image

**Comment by mdt2** [comment]
Great question @rise-erpelding! When RTL is on, the assumption is that the component would show a right-to-left language like Arabic, so the flipping of the UI aligns with that. I agree that calling it Left/Right is confusing in this case. My first thought was to try to name these the way logical properties are handled, but I'm not sure that really applies 1:1. Does that help? I'm definitely open to suggestions 😄

**Review by jawinn — APPROVED** [review]
This looks good and fixes the issue with the tip placement.

I did notice one thing that seems to have regressed, that may be a slightly different bug. It might be worth trying to tackle here as well? Or a followup PR/issue.

In the YML docs, under "**Show on hover**", these don't appear to behave the same way anymore in RTL. These are using the CSS within a `.u-tooltip-showOnHover` class (which seems unusual for our library):

[Older version built on prod](https://opensource.adobe.com/spectrum-css/tooltip.html):
Screenshot 2024-05-07 at 10 02 49 AM

Current local build of main and PR:
Screenshot 2024-05-07 at 10 08 07 AM

**Comment by mdt2** [comment]
@jawinn I can't seem to replicate this, maybe I'm misunderstanding 🤔 Are you looking at "Show on hover" for the [PR deploy of this PR](https://pr-2736--spectrum-css.netlify.app/tooltip)? This is what I see:

Screen Shot 2024-05-07 at 11 09 34 AM

**Comment by jawinn** [comment]
> I can't seem to replicate this, maybe I'm misunderstanding 🤔 Are you looking at "Show on hover" for the [PR deploy of this PR](https://pr-2736--spectrum-css.netlify.app/tooltip)? This is what I see:

Yes, on that PR link. Viewed in Direction RTL.

**Review by jawinn — APPROVED** [review]
Looks great! Thanks for fixing that "Show on hover" issue and for adding documentation.

**Pull request merged**
