### PR TITLE
Tray rsp v3

### PR DESCRIPTION
**Pull request by GarthDB**
## Description

Syncing up with React Spectrum V3 work on Dialog, Modal, and Tray.

It requires https://github.com/adobe/spectrum-css/pull/710

## To-do list

- [x] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x] This pull request is ready to merge.

### CODE REVIEW

**Comment by jianliao** [comment]
@GarthDB Looks like some token are missing which caused `gulp build` failed.

**Comment by GarthDB** [comment]
@jianliao that's really odd, it was working before, and it looks like the variables are there, I'll dig into it.

**Comment by bernhard-adobe** [comment]
Maybe consider some of the RTL support like changing things back to to `inline-size`.

**Comment by bernhard-adobe** [comment]
@jianliao can we please add a VRT for this PR?

**Comment by GarthDB** [comment]
@bernhard-adobe I switch things to `inline` for rtl. Could you give me a review?

**Pull request merged**
