### PR TITLE
updated typography docs to show current Subheading and Detail

### PR DESCRIPTION
**Pull request by NateBaldwinDesign**
## Description

`Subheading` and `Detail` were not shown in docs sufficiently, leading some clients to believe they were not in Spectrum-CSS. I've added simple examples to illustrate the classes.

## Motivation and Context

To ensure designers/engineers do not assume these type styles are not in Spectrum-css

## How Has This Been Tested?

Local testing - docs page updates only

## Screenshots (if appropriate):
image
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by lazd** [comment]
@NateBaldwinDesign can you rebase this? Thanks!

**Comment by lazd** [comment]
I went ahead and rebased this and fixed reference to `Body5` in the article detail example. This is ready to merge.

**Comment by jianliao** [comment]
package-lock.json should be excluded.

**Comment by lazd** [comment]
@jianliao good catch!

**Pull request merged**
