### PR TITLE
chore(storybook): align display viewports for stories

### PR DESCRIPTION
**Pull request by castastrophe**
## Description

This PR's focus is on how components are laid out in storybook's docs and preview frames. This PR also normalizes the heading levels in the VRTs but introduces no other changes to snapshots.

Remove the Dark/RTL snapshot for coachindicator as it incurs no style changes.

Examples on on docs pages and in preview pages will now show the components as centered in the preview window:

**Docs**:
Screenshot 2024-09-19 at 12 13 43 PM

**Preview**:

Screenshot 2024-09-19 at 12 15 15 PM

## How and where has this been tested?

Please tag yourself on the tests you've marked complete to confirm the tests have been run by someone other than the author.

### Validation steps

- [ ] Expect docs page examples to appear centered in their display window
- [ ] Expect alert dialog, dialog, and underlay to appear as fullscreen

### Regression testing

Validate:

1. The documentation pages for at least two other components are still loading, including:

- [ ] The pages render correctly, are accessible, and are responsive.

2. If components have been modified, VRTs have been run on this branch:

- [ ] VRTs have been run and looked at.
- [ ] Any VRT changes have been accepted (by reviewer and/or PR author), or there are no changes.

## To-do list

- [x] I have read the [contribution guidelines](/.github/CONTRIBUTING.md).
- [x] I have updated relevant storybook stories and templates.
- [x] I have tested these changes in Windows High Contrast mode.
- [x] If my change impacts **other components**, I have tested to make sure they don't break.
- [x] If my change impacts **documentation**, I have updated the documentation accordingly.
- [ ] ✨ This pull request is ready to merge. ✨

### CODE REVIEW

**Review by rise-erpelding — COMMENTED** [review]
The components look really nice for the most part! Here are a couple of things that I noticed:

* The Default Modal story on the docs page is aligned oddly in Firefox, and also has a double scroll bar (noticed this in Chrome and Firefox):
modal-docs-page-default-story--firefox
* We were just chatting earlier this week about the Alert Banner being a little short because of `#storybook-root { inline-size: max-content; max-inline-size: 100%; }`, with a centered layout, removing those properties doesn't seem to do anything to help solve that issue. I _think_ going back to a padded layout resolves this, what do we think about doing that for this one component (and if there are others causing similar problems)?

**Review by rise-erpelding — COMMENTED** [review]
Hmmm, I'm still getting this double scroll bar and content stuck to top for Modal in Firefox:

image

and the double scrollbar in Chrome:

image

Do we think that's a blocker for merging? I don't see it in prod:
image


Alert banner looks great though!

**Comment by castastrophe** [comment]
@rise-erpelding I just pushed up an update that removes the `-moz-available` fallback in modal because it seems to be broken (the 100vh is working better in FF) and I set an overflow: hidden on the docs-story container which seems to help a lot with the additional scrollbar showing up. Please let me know if this corrects the issue for you as well!

**Review by rise-erpelding — APPROVED** [review]
Looks great! Those issues with modal have been resolved!

**Review by cdransf — APPROVED** [review]

**Review by pfulton — APPROVED** [review]

**Pull request merged**
