### PR TITLE
Slider: remove cursor: pointer and reenable active style

### LINKED ISSUE #965: Slider shouldn't have `cursor: pointer` or similar
## Description

The native `<input type="range">` element doesn't change the default pointer. The Spectrum slider shouldn't either.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/slider.html
2. Hover/Drag a slider
3. A "dragging" cursor is displayed.

## Expected behavior

The cursor shouldn't change.

## Environment
 - **Spectrum CSS version:** 74000c8
 - **Browser(s) and OS(s):** 85.0.4183.102, macOS 10.15

## Additional context

Trying to upstream this to minimize changes in the CSS "fork" in the React Spectrum repo: https://github.com/adobe/react-spectrum/pull/1083

synced to jira: https://jira.corp.adobe.com/browse/SDS-7659

### LINKED ISSUE #966: Slider handle's active style doesn't match Spectrum spec
## Description

The Slider component's active style of the handle doesn't match the mockups in the Spectrum XD file.

## Steps to reproduce

1. https://opensource.adobe.com/spectrum-css/slider.html
2. Drag a slider
3. The handle should have a thicker border when dragging/clicking.

## Expected behavior (when clicking/dragging)

Bildschirmfoto 2020-09-23 um 10 56 02

## Current behavior (when clicking/dragging)

Bildschirmfoto 2020-09-23 um 11 03 05

## Environment
 - **Spectrum CSS version:** 74000c8
 - **Browser(s) and OS(s):** 85.0.4183.102, macOS 10.15

## Additional context

Trying to upstream this to minimize changes in the CSS "fork" in the React Spectrum repo: https://github.com/adobe/react-spectrum/pull/1083

synced to jira: https://jira.corp.adobe.com/browse/SDS-7660

### PR DESCRIPTION
**Pull request by mischnic**
## Description

Closes #965, Closes #966 

## How and where has this been tested?
 - **How this was tested:** See screenshots in the issues
 - **Browser(s) and OS(s) this was tested with:**  85.0.4183.102, macOS 10.15

## Screenshots

Bildschirmfoto 2020-09-23 um 10 56 02

## To-do list
- [x] If my change impacts other components, I have tested to make sure they don't break (Dial).
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).

- [x] This pull request is ready to merge.

### CODE REVIEW

**Review by GarthDB — CHANGES_REQUESTED** [review]
Could you resolve conflicts with `main` and is there a reason why you made 2 different prs for slider instead of combining them?

**Comment by mischnic** [comment]
Done. No reason in particular...

**Comment by GarthDB** [comment]
Ok. We discussed some of these changes with Design in a recent meeting. I would like to go over it with the Design team before I move forward with it. I'll bring it up in Design Workshop with them tomorrow.

**Review by GarthDB — APPROVED** [review]

**Comment by mischnic** [comment]
Just a heads up: I will update this later today so that activating the slider by clicking on the track also adds the active style

Sep-24-2020 09-30-26

**Comment by mischnic** [comment]
No CSS change was necessary, just needed to add the `is-dragging` class to the handle on `mousedown`.

**Pull request merged**
