### PR TITLE
Fix yarn optional-dependency issue.

### PR DESCRIPTION
**Pull request by jianliao**
## Description
Using `.yarnrc` file to enforce `workspaces` and `ignore-optional` always true for spectrum-css.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by lazd** [comment]
You're awesome!

Why is `workspaces-experimental true` required? It seemed to be working without it before?

**Comment by jianliao** [comment]
I am wondering why you don't need it, too.

**Comment by lazd** [comment]
Based on [the docs here](https://yarnpkg.com/lang/en/docs/workspaces/), this looks good! Ready to merge?

**Comment by jianliao** [comment]
Yes, please merge.

**Pull request merged**
