### PR TITLE
refactor: replace loudness API with quiet for PickerButton and InfieldButton

### PR DESCRIPTION
**Pull request by yosevu**
## Description

These changes impact 4 components: PickerButton, InfieldButotn, Combobox, DatePicker

- This replaces Loudness API `--low`, `--medium`, and `--high` with `--quiet`.
- It updates the CSS selectors only and does not rename the loudness tokens.
- Other variants than loudness/quiet should not be affected visually by this PR.

CSS-234

## References

[CSS-228](https://jira.corp.adobe.com/browse/CSS-228)
[CSS-234](https://jira.corp.adobe.com/browse/CSS-234)
[Slack thread](https://adobedesign.slack.com/archives/G019JTYMT6H/p1660319825337619)

image

## How and where has this been tested?
 - **How this was tested:** 
 - **Browser(s) and OS(s) this was tested with:** 

### InField Button

Screen Shot 2022-10-20 at 10 02 03 PM

### Date Picker with PickerButton

Screen Shot 2022-10-20 at 10 08 31 PM

### Combobox with PickerButton
Screen Shot 2022-10-20 at 10 07 02 PM

## To-do list

- [x] If my change impacts other components, I have tested to make sure they don't break.
- [x] If my change impacts documentation, I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING document](/.github/CONTRIBUTING.md).
- [ ] I have tested these changes in Windows High Contrast mode.

- [ ] This pull request is ready to merge.

### CODE REVIEW

**Comment by pfulton** [comment]
Pulling in @Westbrook to be sure that he's aware of the things that will be changing here.

**Review by pfulton — CHANGES_REQUESTED** [review]
This looks great, @yosevu. Well done.

One request: can you please add Migration Guide documentation for each of the components affected by this change? We probably want to say what's changing and how folks can switch to what's new. I'd write this from the perspective of if you were a developer who consumed these components and needed to know what changed.

We've done similar migration docs in ActionButton, if you want to use that as a guide: https://opensource.adobe.com/spectrum-css/actionbutton.html#migrationguide

**Comment by yosevu** [comment]
> This looks great, @yosevu. Well done.
> 
> One request: can you please add Migration Guide documentation for each of the components affected by this change? We probably want to say what's changing and how folks can switch to what's new. I'd write this from the perspective of if you were a developer who consumed these components and needed to know what changed.
> 
> We've done similar migration docs in ActionButton, if you want to use that as a guide: https://opensource.adobe.com/spectrum-css/actionbutton.html#migrationguide

Will do.

**Review by pfulton — APPROVED** [review]
Looks great. Thanks for taking care of this, @yosevu

**Pull request merged**
